### ISSUE TITLE
Micrometer metrics for quarkus vertx

### ISSUE THREAD

**Issue by ramesshh** [quarkusio/quarkus-quickstarts#183] opened 2019-05-01 23:52 UTC
Could not able to get micrometer metrics from quarkus vertx.
Followed this documentation 
https://vertx.io/docs/vertx-micrometer-metrics/java/

and below code 
  ``` 
VertxOptions vertxOptions = new VertxOptions().setMetricsOptions(
                new MicrometerMetricsOptions()
                        .setInfluxDbOptions(new VertxInfluxDbOptions().setEnabled(true)
                                .setUri("http://localhost:8086")
                                .setDb("quarkusdb").setUserName("admin").setPassword("admin"))
                        .setEnabled(true));
        Vertx vertx = Vertx.vertx(vertxOptions);
        this.webClient = WebClient.create(vertx); 
```

**Comment by gsmet** [comment] 2019-05-02 10:19
@cescoffier I think your expertise is needed there :).

**Comment by tsegismont** [comment] 2019-05-03 08:09
@ramesshh to determine if the Micrometer metrics extension is gathering any metric, you may add this to your code:

```
MetricsService metricsService = MetricsService.create(vertx);
JsonObject metrics = metricsService.getMetricsSnapshot();
System.out.println(metrics);
```

I can't see anything obviously wrong in your snippet. Could you share a reproducer on GitHub?

**Comment by ramesshh** [comment] 2019-05-03 22:23
@tsegismont - Am able to see the metrics with the below code 
```
 {"vertx.http.client.bytesReceived":[{"tags":{},"type":"summary","count":0,"total":0.0,"mean":0.0,"max":217.0}],"vertx.http.client.bytesSent":[{"tags":{},"type":"summary","count":0,"total":0.0,"mean":0.0,"max":0.0}],"vertx.http.client.connections":[{"tags":{},"type":"gauge","value":0.0}],"vertx.http.client.requestCount":[{"tags":{"method":"GET"},"type":"counter","count":0.0}],"vertx.http.client.requests":[{"tags":{"method":"GET"},"type":"gauge","value":0.0}],"vertx.http.client.responseCount":[{"tags":{"code":"200","method":"GET"},"type":"counter","count":0.0}],"vertx.http.client.responseTime":[{"tags":{"code":"200","method":"GET"},"type":"timer","count":0,"totalTimeMs":0.0,"meanMs":0.0,"maxMs":47.314237}]}
```

**Comment by tsegismont** [comment] 2019-05-04 07:58
@jotak does that ring a bell?

@ramesshh please share a reproducer

**Comment by jotak** [comment] 2019-05-04 18:51
I don't see any obvious issue with the code. I'm not familiar with quarkus so I can't say if something could not work with micrometers push jobs to influx... Definitely a reproducer would help.

**Comment by ramesshh** [comment] 2019-05-05 02:04
First things, apologize for not posting the full project here due to some limitations
But here is the full class that I think reproduces the issue

**Code:**

`
package org.acme.quarkus.sample;

import io.micrometer.core.instrument.composite.CompositeMeterRegistry;
import io.quarkus.vertx.ConsumeEvent;
import io.vertx.axle.core.Context;
import io.vertx.axle.core.Vertx;
import io.vertx.axle.core.eventbus.EventBus;
import io.vertx.axle.core.eventbus.Message;
import io.vertx.axle.ext.web.client.WebClient;
import io.vertx.core.VertxOptions;
import io.vertx.core.eventbus.EventBusOptions;
import io.vertx.core.http.HttpMethod;
import io.vertx.core.http.RequestOptions;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.client.WebClientOptions;
import io.vertx.micrometer.MetricsService;
import io.vertx.micrometer.MicrometerMetricsOptions;
import io.vertx.micrometer.VertxInfluxDbOptions;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import java.util.concurrent.CompletionStage;

@Path("/")
public class HelloResource {

    protected Logger logger = LoggerFactory.getLogger(getClass());

    private WebClient client;

    @Inject
    Vertx vertx;

    @Inject
    EventBus bus;

    @PostConstruct
    void initialize() {

       /* VertxInfluxDbOptions vertxInfluxDbOptions = new VertxInfluxDbOptions().setEnabled(true)
                .setUri("http://localhost:8086")
                .setDb("mydb").setUserName("admin").setPassword("password");

        VertxOptions vertxOptions = new VertxOptions().setMetricsOptions(
                new MicrometerMetricsOptions()
                        .setInfluxDbOptions(vertxInfluxDbOptions)
                        .setEnabled(true));

        vertx = Vertx.vertx(vertxOptions);
        bus = vertx.eventBus();*/

        logger.info("Is Vertx Metrics Enabled -  {}",vertx.isMetricsEnabled());
        logger.info("Is EventBus Metrics Enabled  -  {} ",bus.isMetricsEnabled());

        this.client = WebClient.create(vertx,
                new WebClientOptions().setDefaultHost("localhost").setDefaultPort(8080).setSsl(false));
    }

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/rest/api/{name}")
    public CompletionStage<String> getStarWarsCharacter(@PathParam("name") String name) {
        logMeterics();
        return client.get("/hello/" + name)
                .send()
                .thenApply(resp -> {
                    if (resp.statusCode() == 200) {
                        return resp.bodyAsString();
                    } else {
                        return "error";
                    }
                });
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/hello/{name}")
    public CompletionStage<String> greeting(@PathParam("name") String name) {
        logMeterics();
        return bus.<String>send("greeting", name)
                .thenApply(Message::body);
    }

    private void logMeterics(){
        MetricsService metricsService = MetricsService.create(vertx.getDelegate());
        JsonObject metrics = metricsService.getMetricsSnapshot();
        logger.info("metrics are {}",metrics);
    }

    @ConsumeEvent("greeting")
    public String greetingEventBus(String name) {
        return "Hello " + name;
    }
}
`

**And Installed below features -  And added vertx micrometer and micrometer with influx.**
`2019-05-04 21:53:58,574 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, smallrye-metrics, smallrye-rest-client, vertx]
`

**My Requests**
1. http://localhost:8080/hello/ramesh
2. http://localhost:8080/rest/api/ramesh

**Observations:**

- w/o Vertx micrometer and Micrometer influx dependencies, functionally everything works fine, but metrics are null from logs.  Response from both the requests are "hello ramesh"
- w/ Vertx micrometer and Micrometer influx dependencies, added VertxOptions, VertxInflux and  commenting the Inject annotations from Vertx, EventBus objects.

**Comment by ramesshh** [comment] 2019-05-10 11:56
@jotak - Do you see any issue with my code or way of implementation?

**Comment by jotak** [comment] 2019-05-10 14:40
It doesn't look related to the metrics. I took your code snippet and modified it to not enable metrics but I keep your vertx/bus reassignment, and I get the same error:

```
    @PostConstruct
    void initialize() {
/*
       VertxInfluxDbOptions vertxInfluxDbOptions = new VertxInfluxDbOptions().setEnabled(true)
                .setUri("http://localhost:8086")
                .setDb("mydb").setUserName("admin").setPassword("password");

        VertxOptions vertxOptions = new VertxOptions().setMetricsOptions(
                new MicrometerMetricsOptions()
                        .setInfluxDbOptions(vertxInfluxDbOptions)
                        .setEnabled(true));*/

        vertx = Vertx.vertx();
        bus = vertx.eventBus();

        logger.info("Is Vertx Metrics Enabled -  {}",vertx.isMetricsEnabled());
        logger.info("Is EventBus Metrics Enabled  -  {} ",bus.isMetricsEnabled());

        this.client = WebClient.create(vertx,
            new WebClientOptions().setDefaultHost("localhost").setDefaultPort(8080).setSsl(false));
    }
```

=>
```
2019-05-10 16:34:06,673 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002025: Unknown exception while executing GET /hello/toto: java.util.concurrent.CompletionException: (NO_HANDLERS,-1) No handlers for address greeting
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110)
	at org.acme.quickstart.GreetingResource.greeting(GreetingResource.java:89)

```

So metrics doesn't play any role there. It looks more like something proper to vertx+quarkus? Personally I'm not qualified in these domain (first time with quarkus for me :-) ) maybe @tsegismont or @cescoffier could help?

**Comment by ramesshh** [comment] 2019-05-11 01:05
Yes. I think the vertx and eventBus beans were created from VertxProducer. ConsumeEvent annotation is defined to read from those beans. The sender from my code is sending to one eventBus, whereas method that has consume event annotation listening on another event Bus.

I think quarkus framework team needs to provide the following,
1. Provide an option to create multiple vertx, eventBus option
2. Provide the capability to configure metrics for vertx. Currently, no vertx metrics options is enabled.

@tsegismont @cescoffier - any suggestions in this regard will be appreciated.

Thanks

**Comment by cescoffier** [comment] 2019-05-11 18:11
@ramesshh 

1. just use `Vertx.vertx()` with the option you need. Note that the default instances can be configured from the `application.properties` file
2. By default, Quarkus metrics are collected using SmallRye Metrics, there is no integration of SmallRye Metrics with Vert.x yet (but contributions are welcome).

@jotak The error you see is because someone sent a message to the address `greeting` but no one is listening.

**Closed** 2022-11-10 07:39 UTC
Labels: invalid
